In [4]:
import pandas as pd

df = pd.read_csv(r"C:\Users\91727\Downloads\Delivery_Logistics.csv")

In [7]:
df.head()
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  object
 10  expected_time_hours  25000 non-null  object
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
dtypes: float64(4), int64(1), object(10)
memory usage: 2.9+ MB

,delivery_id,distance_km,package_weight_kg,delivery_rating,delivery_cost
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,150.390436,25.145898,3.666000,864.944579
std,7212.732314,86.409745,14.368663,1.149964,435.712593
min,250.990000,3.600000,0.670000,1.000000,95.667400
25%,6250.750000,75.900000,12.680000,3.000000,490.800000
50%,12500.500000,151.000000,25.145000,4.000000,867.535000
75%,18750.250000,224.900000,37.660000,5.000000,1237.910000
max,24750.010000,297.100000,49.520000,5.000000,1632.720600

In [8]:
df.dtypes

delivery_id            float64
delivery_partner        object
package_type            object
vehicle_type            object
delivery_mode           object
region                  object
weather_condition       object
distance_km            float64
package_weight_kg      float64
delivery_time_hours     object
expected_time_hours     object
delayed                 object
delivery_status         object
delivery_rating          int64
delivery_cost          float64
dtype: object

In [10]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [11]:
df.columns

Index(['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type',
       'delivery_mode', 'region', 'weather_condition', 'distance_km',
       'package_weight_kg', 'delivery_time_hours', 'expected_time_hours',
       'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost'],
      dtype='object')

In [12]:
df.head(10).to_string()

'   delivery_id  delivery_partner      package_type vehicle_type delivery_mode   region weather_condition  distance_km  package_weight_kg            delivery_time_hours            expected_time_hours delayed delivery_status  delivery_rating  delivery_cost\n0       250.99         delhivery  automobile parts         bike      same day     west             clear        297.0              46.96  1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000008      no       delivered                3      1632.7206\n1       250.99        xpressbees         cosmetics       ev van       express  central              cold         89.6              47.39  1970-01-01 00:00:00.000000002  1970-01-01 00:00:00.000000003      no       delivered                5       640.1700\n2       250.99         shadowfax         groceries        truck       two day     east             rainy        273.5              26.89  1970-01-01 00:00:00.000000010  1970-01-01 00:00:00.000000016      no       delivered                4      1448.1700\n3       250.99               dhl       electronics       ev van      same day     east              cold        269.7              12.69  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no       delivered                3      1486.5700\n4       250.99               dhl          clothing          van       two day    north             foggy        256.7              37.02  1970-01-01 00:00:00.000000009  1970-01-01 00:00:00.000000016      no       delivered                4      1394.5600\n5       250.99  amazon logistics         documents      ev bike       express     west             rainy         48.4              33.15  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000002     yes         delayed                3       391.4500\n6       250.99         delhivery         groceries      scooter      same day  central             clear        198.3              43.79  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no       delivered                3      1222.8700\n7       250.99        xpressbees     fragile items          van      same day    north              cold        114.6              42.63  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000008      no       delivered                3       800.8900\n8       250.99         blue dart          clothing          van      same day    south               hot        142.4              14.06  1970-01-01 00:00:00.000000005  1970-01-01 00:00:00.000000008      no       delivered                5       854.1800\n9       250.99         delhivery          pharmacy        truck      same day     east             foggy         47.1              29.28  1970-01-01 00:00:00.000000003  1970-01-01 00:00:00.000000008      no       delivered                5       423.3400'

In [15]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width',200)

df[[
    "delivery_id",
    "delivery_time_hours",
    "expected_time_hours",
    "delayed",
    "delivery_status"
]].head(10)

   delivery_id            delivery_time_hours            expected_time_hours delayed delivery_status
0       250.99  1970-01-01 00:00:00.000000008  1970-01-01 00:00:00.000000008      no       delivered
1       250.99  1970-01-01 00:00:00.000000002  1970-01-01 00:00:00.000000003      no       delivered
2       250.99  1970-01-01 00:00:00.000000010  1970-01-01 00:00:00.000000016      no       delivered
3       250.99  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no       delivered
4       250.99  1970-01-01 00:00:00.000000009  1970-01-01 00:00:00.000000016      no       delivered
5       250.99  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000002     yes         delayed
6       250.99  1970-01-01 00:00:00.000000006  1970-01-01 00:00:00.000000008      no       delivered
7       250.99  1970-01-01 00:00:00.000000004  1970-01-01 00:00:00.000000008      no       delivered
8       250.99  1970-01-01 00:00:00.000000005  1970-01-01 00:00:00.000000008      no       delivered
9       250.99  1970-01-01 00:00:00.000000003  1970-01-01 00:00:00.000000008      no       delivered

In [16]:
print(df["delivery_time_hours"].unique()[:20])
print(df["expected_time_hours"].unique()[:20])

['1970-01-01 00:00:00.000000008' '1970-01-01 00:00:00.000000002'
 '1970-01-01 00:00:00.000000010' '1970-01-01 00:00:00.000000006'
 '1970-01-01 00:00:00.000000009' '1970-01-01 00:00:00.000000004'
 '1970-01-01 00:00:00.000000005' '1970-01-01 00:00:00.000000003'
 '1970-01-01 00:00:00.000000012' '1970-01-01 00:00:00.000000011'
 '1970-01-01 00:00:00.000000007' '1970-01-01 00:00:00.000000013'
 '1970-01-01 00:00:00.000000000' '1970-01-01 00:00:00.000000001'
 '1970-01-01 00:00:00.000000014' '1970-01-01 00:00:00.000000016'
 '1970-01-01 00:00:00.000000015' '1970-01-01 00:00:00.000000017'
 '1970-01-01 00:00:00.000000018' '1970-01-01 00:00:00.000000019']
['1970-01-01 00:00:00.000000008' '1970-01-01 00:00:00.000000003'
 '1970-01-01 00:00:00.000000016' '1970-01-01 00:00:00.000000002'
 '1970-01-01 00:00:00.000000006' '1970-01-01 00:00:00.000000024'
 '1970-01-01 00:00:00.000000007' '1970-01-01 00:00:00.000000004'
 '1970-01-01 00:00:00.000000005']

In [17]:
print("Total rows:", len(df))
print("Unique delivery IDs:", df["delivery_id"].nunique())
print("Duplicate delivery IDs:", df["delivery_id"].duplicated().sum())

Total rows: 25000
Unique delivery IDs: 24502
Duplicate delivery IDs: 498

In [20]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df[df["delivery_id"].duplicated(keep=False)].sort_values("delivery_id").head(20)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
159,250.99,amazon logistics,furniture,truck,standard,north,hot,42.6,44.55,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000024,no,delivered,4,346.6500
160,250.99,ecom express,automobile parts,ev bike,standard,east,foggy,149.9,23.31,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000024,no,delivered,4,819.4300
161,250.99,shadowfax,clothing,scooter,standard,west,rainy,8.4,44.16,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000024,no,delivered,4,174.4800
162,250.99,dhl,documents,ev bike,two day,east,hot,230.8,30.01,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000016,no,delivered,4,1244.0300
163,250.99,dhl,clothing,bike,express,west,clear,93.0,9.37,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,4,543.1100
164,250.99,dhl,electronics,van,two day,west,clear,10.4,4.59,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000016,no,delivered,4,95.6674
165,250.99,amazon logistics,pharmacy,truck,two day,north,hot,194.9,2.42,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,4,981.7600
166,250.99,ekart,documents,scooter,express,west,rainy,182.1,2.26,1970-01-01 00:00:00.000000011,1970-01-01 00:00:00.000000005,yes,delayed,2,967.2800
167,250.99,blue dart,cosmetics,ev bike,standard,south,clear,38.8,40.89,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000024,no,delivered,4,316.6700
168,250.99,dhl,groceries,bike,two day,north,cold,55.2,6.78,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000016,no,delivered,3,296.3400
169,250.99,delhivery,pharmacy,truck,express,east,stormy,223.3,44.36,1970-01-01 00:00:00.000000012,1970-01-01 00:00:00.000000006,yes,failed,1,1299.5800
170,250.99,delhivery,electronics,truck,express,west,hot,46.2,14.83,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000002,no,delivered,5,325.4900
171,250.99,delhivery,documents,ev bike,two day,south,hot,3.6,49.52,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000016,no,delivered,5,163.3900
172,250.99,xpressbees,groceries,scooter,express,north,hot,297.1,22.00,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000008,no,delivered,5,1615.5000
173,250.99,xpressbees,electronics,bike,express,central,hot,87.8,7.72,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000003,no,delivered,5,512.1600
174,250.99,xpressbees,groceries,truck,express,central,hot,267.4,11.53,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000007,yes,delayed,2,1421.5900
175,250.99,fedex,furniture,ev van,two day,east,stormy,124.8,10.84,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,656.5200
176,250.99,xpressbees,groceries,ev bike,express,south,clear,288.9,8.30,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000007,no,delivered,4,1519.4000
177,250.99,blue dart,furniture,scooter,two day,central,hot,129.5,39.84,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,4,767.0200

In [24]:
df["delivery_id"].value_counts().head(10)

delivery_id
250.99      250
24750.01    250
252.00        1
16582.00      1
16591.00      1
16590.00      1
16589.00      1
16588.00      1
16587.00      1
16586.00      1
Name: count, dtype: int64

In [26]:
print("Minimum ID:", df["delivery_id"].min())
print("Maximum ID:", df["delivery_id"].max())
print("Data type:", df["delivery_id"].dtype)

Minimum ID: 250.99
Maximum ID: 24750.01
Data type: float64

In [27]:
print(df["delivery_time_hours"].iloc[0])
print(type(df["delivery_time_hours"].iloc[0]))

print(df["expected_time_hours"].iloc[0])
print(type(df["expected_time_hours"].iloc[0]))

1970-01-01 00:00:00.000000008
<class 'str'>
1970-01-01 00:00:00.000000008
<class 'str'>

In [28]:
print(df["delivery_time_hours"].value_counts().head(20))

delivery_time_hours
1970-01-01 00:00:00.000000006    3118
1970-01-01 00:00:00.000000005    3011
1970-01-01 00:00:00.000000007    2921
1970-01-01 00:00:00.000000004    2571
1970-01-01 00:00:00.000000008    2386
1970-01-01 00:00:00.000000003    2352
1970-01-01 00:00:00.000000009    1875
1970-01-01 00:00:00.000000002    1668
1970-01-01 00:00:00.000000010    1371
1970-01-01 00:00:00.000000011    1039
1970-01-01 00:00:00.000000001     963
1970-01-01 00:00:00.000000012     649
1970-01-01 00:00:00.000000013     371
1970-01-01 00:00:00.000000000     255
1970-01-01 00:00:00.000000014     247
1970-01-01 00:00:00.000000015     116
1970-01-01 00:00:00.000000016      51
1970-01-01 00:00:00.000000017      26
1970-01-01 00:00:00.000000018       7
1970-01-01 00:00:00.000000019       3
Name: count, dtype: int64

In [29]:
print(df["expected_time_hours"].value_counts().head(20))

expected_time_hours
1970-01-01 00:00:00.000000016    6302
1970-01-01 00:00:00.000000008    6287
1970-01-01 00:00:00.000000024    6186
1970-01-01 00:00:00.000000005    1080
1970-01-01 00:00:00.000000007    1051
1970-01-01 00:00:00.000000004    1037
1970-01-01 00:00:00.000000003    1029
1970-01-01 00:00:00.000000002    1015
1970-01-01 00:00:00.000000006    1013
Name: count, dtype: int64

In [30]:
delivery_time_temp = pd.to_datetime(df["delivery_time_hours"])
expected_time_temp = pd.to_datetime(df["expected_time_hours"])

print("Delivery time range:",
      delivery_time_temp.dt.nanosecond.min(),
      "to",
      delivery_time_temp.dt.nanosecond.max())

print("Expected time range:",
      expected_time_temp.dt.nanosecond.min(),
      "to",
      expected_time_temp.dt.nanosecond.max())

Delivery time range: 0 to 19
Expected time range: 2 to 24

In [31]:
df["delivery_time_hours_clean"] = delivery_time_temp.dt.nanosecond
df["expected_time_hours_clean"] = expected_time_temp.dt.nanosecond

In [32]:
print(df[[
    "delivery_time_hours",
    "delivery_time_hours_clean",
    "expected_time_hours",
    "expected_time_hours_clean"
]].head(10))

             delivery_time_hours  delivery_time_hours_clean            expected_time_hours  expected_time_hours_clean
0  1970-01-01 00:00:00.000000008                          8  1970-01-01 00:00:00.000000008                          8
1  1970-01-01 00:00:00.000000002                          2  1970-01-01 00:00:00.000000003                          3
2  1970-01-01 00:00:00.000000010                         10  1970-01-01 00:00:00.000000016                         16
3  1970-01-01 00:00:00.000000006                          6  1970-01-01 00:00:00.000000008                          8
4  1970-01-01 00:00:00.000000009                          9  1970-01-01 00:00:00.000000016                         16
5  1970-01-01 00:00:00.000000004                          4  1970-01-01 00:00:00.000000002                          2
6  1970-01-01 00:00:00.000000006                          6  1970-01-01 00:00:00.000000008                          8
7  1970-01-01 00:00:00.000000004                          4  1970-01-01 00:00:00.000000008                          8
8  1970-01-01 00:00:00.000000005                          5  1970-01-01 00:00:00.000000008                          8
9  1970-01-01 00:00:00.000000003                          3  1970-01-01 00:00:00.000000008                          8

In [33]:
print(df[[
    "delivery_time_hours_clean",
    "expected_time_hours_clean"
]].describe())

       delivery_time_hours_clean  expected_time_hours_clean
count               25000.000000               25000.000000
mean                    6.248040                  13.107680
std                     3.140935                   7.559024
min                     0.000000                   2.000000
25%                     4.000000                   8.000000
50%                     6.000000                   8.000000
75%                     8.000000                  16.000000
max                    19.000000                  24.000000

In [34]:
print ("Delivery time = 0:", (df["delivery_time_hours_clean"] == 0).sum())

Delivery time = 0: 255

In [37]:
df[df["delivery_time_hours_clean"] == 0][[
    "delivery_time_hours_clean",
    "expected_time_hours_clean",
    "distance_km",
    "delivery_mode",
    "delivery_status",
    "delayed"
]].head(10)

      delivery_time_hours_clean  expected_time_hours_clean  distance_km delivery_mode delivery_status delayed
87                            0                         16          3.6       two day       delivered      no
136                           0                          8          8.7      same day       delivered      no
181                           0                          8          9.9      same day       delivered      no
303                           0                          8         21.0      same day       delivered      no
574                           0                          2         41.7       express       delivered      no
823                           0                          8         13.2      same day       delivered      no
836                           0                         16         24.5       two day       delivered      no
871                           0                          8         33.3      same day       delivered      no
947                           0                         24          9.0      standard       delivered      no
1046                          0                          8         10.5      same day       delivered      no

In [40]:
print("Delivery time = 0:", (df["delivery_time_hours_clean"] == 0).sum())

Delivery time = 0: 255

In [41]:
Q1 = df["delivery_time_hours_clean"].quantile(0.25)
Q3 = df["delivery_time_hours_clean"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower bound:", lower_bound)
print("Upper bound:", upper_bound)

Q1: 4.0
Q3: 8.0
IQR: 4.0
Lower bound: -2.0
Upper bound: 14.0

In [42]:
outliers = df[df["delivery_time_hours_clean"] > upper_bound]

print("Number of outliers:", len(outliers))

Number of outliers: 203

In [43]:
print(outliers[[
    "delivery_time_hours_clean",
    "expected_time_hours_clean",
    "distance_km",
    "delivery_mode",
    "delivery_status",
    "delayed"
]].head(20))

      delivery_time_hours_clean  expected_time_hours_clean  distance_km delivery_mode delivery_status delayed
230                          16                          8        262.9      same day         delayed     yes
356                          15                          7        293.3       express         delayed     yes
415                          15                          7        270.7       express         delayed     yes
438                          15                         24        267.7      standard       delivered      no
622                          15                          8        284.9      same day         delayed     yes
778                          16                         16        264.4       two day         delayed     yes
882                          15                         16        247.4       two day       delivered      no
1169                         16                          8        255.0      same day         delayed     yes
1276                         15                          7        293.2       express         delayed     yes
1354                         16                         16        261.1       two day         delayed     yes
1428                         15                          7        272.5       express         delayed     yes
1527                         17                         24        295.0      standard       delivered      no
1691                         16                          8        261.8      same day         delayed     yes
1768                         16                          7        277.4       express         delayed     yes
1880                         17                          7        276.2       express         delayed     yes
2209                         15                         16        292.0       two day       delivered      no
2260                         15                         16        288.3       two day       delivered      no
2327                         15                          8        292.3      same day         delayed     yes
2738                         16                         24        291.7      standard       delivered      no
2961                         15                          7        285.7       express          failed     yes

In [44]:
categorical_columns = [
    "delivery_partner",
    "package_type",
    "vehicle_type",
    "delivery_mode",
    "region",
    "weather_condition",
    "delayed",
    "delivery_status"
]

for col in categorical_columns:
    print("\n", col)
    print(df[col].unique())

 delivery_partner
['delhivery' 'xpressbees' 'shadowfax' 'dhl' 'amazon logistics' 'blue dart'
 'fedex' 'ecom express' 'ekart']

 package_type
['automobile parts' 'cosmetics' 'groceries' 'electronics' 'clothing'
 'documents' 'fragile items' 'pharmacy' 'furniture']

 vehicle_type
['bike' 'ev van' 'truck' 'van' 'ev bike' 'scooter']

 delivery_mode
['same day' 'express' 'two day' 'standard']

 region
['west' 'central' 'east' 'north' 'south']

 weather_condition
['clear' 'cold' 'rainy' 'foggy' 'hot' 'stormy']

 delayed
['no' 'yes']

 delivery_status
['delivered' 'delayed' 'failed']

In [45]:
numerical_columns = [
    "distance_km",
    "package_weight_kg",
    "delivery_rating",
    "delivery_cost"
]

for col in numerical_columns:
    print("\n", col)
    print("Min:", df[col].min())
    print("Max:", df[col].max())
    print("Mean:", df[col].mean())

 distance_km
Min: 3.6
Max: 297.1
Mean: 150.390436

 package_weight_kg
Min: 0.67
Max: 49.52
Mean: 25.145897599999998

 delivery_rating
Min: 1
Max: 5
Mean: 3.666

 delivery_cost
Min: 95.6674
Max: 1632.7206
Mean: 864.9445787999999

In [46]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

columns_to_normalize = [
    "distance_km",
    "package_weight_kg",
    "delivery_cost"
]

df[[col + "_normalized" for col in columns_to_normalize]] = scaler.fit_transform(
    df[columns_to_normalize]
)

In [47]:
print(df[[
    "distance_km",
    "distance_km_normalized",
    "package_weight_kg",
    "package_weight_kg_normalized",
    "delivery_cost",
    "delivery_cost_normalized"
]].head(10))

   distance_km  distance_km_normalized  package_weight_kg  package_weight_kg_normalized  delivery_cost  delivery_cost_normalized
0        297.0                0.999659              46.96                      0.947595      1632.7206                  1.000000
1         89.6                0.293015              47.39                      0.956397       640.1700                  0.354251
2        273.5                0.919591              26.89                      0.536745      1448.1700                  0.879932
3        269.7                0.906644              12.69                      0.246059      1486.5700                  0.904915
4        256.7                0.862351              37.02                      0.744115      1394.5600                  0.845054
5         48.4                0.152641              33.15                      0.664893       391.4500                  0.192435
6        198.3                0.663373              43.79                      0.882702      1222.8700                  0.733353
7        114.6                0.378194              42.63                      0.858956       800.8900                  0.458815
8        142.4                0.472913              14.06                      0.274104       854.1800                  0.493485
9         47.1                0.148211              29.28                      0.585670       423.3400                  0.213182

In [48]:
print(df[[
    "distance_km_normalized",
    "package_weight_kg_normalized",
    "delivery_cost_normalized"
]].describe())

       distance_km_normalized  package_weight_kg_normalized  delivery_cost_normalized
count            25000.000000                  25000.000000              25000.000000
mean                 0.500138                      0.501042                  0.500488
std                  0.294411                      0.294138                  0.283473
min                  0.000000                      0.000000                  0.000000
25%                  0.246337                      0.245855                  0.257072
50%                  0.502215                      0.501024                  0.502174
75%                  0.754003                      0.757216                  0.743138
max                  1.000000                      1.000000                  1.000000

In [49]:
df["delivery_time_hours"] = df["delivery_time_hours_clean"]
df["expected_time_hours"] = df["expected_time_hours_clean"]

In [50]:
df.drop(
    columns=["delivery_time_hours_clean", "expected_time_hours_clean"],
    inplace=True
)

In [51]:
df.dtypes

delivery_id                     float64
delivery_partner                 object
package_type                     object
vehicle_type                     object
delivery_mode                    object
region                           object
weather_condition                object
distance_km                     float64
package_weight_kg               float64
delivery_time_hours               int32
expected_time_hours               int32
delayed                          object
delivery_status                  object
delivery_rating                   int64
delivery_cost                   float64
distance_km_normalized          float64
package_weight_kg_normalized    float64
delivery_cost_normalized        float64
dtype: object

In [52]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())

Rows: 25000
Columns: 18
Missing values: 0

In [53]:
print(df.head())

   delivery_id delivery_partner      package_type vehicle_type delivery_mode   region weather_condition  distance_km  package_weight_kg  delivery_time_hours  expected_time_hours delayed  \
0       250.99        delhivery  automobile parts         bike      same day     west             clear        297.0              46.96                    8                    8      no
1       250.99       xpressbees         cosmetics       ev van       express  central              cold         89.6              47.39                    2                    3      no
2       250.99        shadowfax         groceries        truck       two day     east             rainy        273.5              26.89                   10                   16      no
3       250.99              dhl       electronics       ev van      same day     east              cold        269.7              12.69                    6                    8      no
4       250.99              dhl          clothing          van       two day    north             foggy        256.7              37.02                    9                   16      no

  delivery_status  delivery_rating  delivery_cost  distance_km_normalized  package_weight_kg_normalized  delivery_cost_normalized
0       delivered                3      1632.7206                0.999659                      0.947595                  1.000000
1       delivered                5       640.1700                0.293015                      0.956397                  0.354251
2       delivered                4      1448.1700                0.919591                      0.536745                  0.879932
3       delivered                3      1486.5700                0.906644                      0.246059                  0.904915
4       delivered                4      1394.5600                0.862351                      0.744115                  0.845054

In [54]:
print(df.columns.tolist())

['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type', 'delivery_mode', 'region', 'weather_condition', 'distance_km', 'package_weight_kg', 'delivery_time_hours', 'expected_time_hours', 'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost', 'distance_km_normalized', 'package_weight_kg_normalized', 'delivery_cost_normalized']

In [55]:
df.to_csv("logistics_delivery_cleaned.csv", index=False)

In [56]:
import os

print(os.path.abspath("logistics_delivery_cleaned.csv"))
print("File exists:", os.path.exists("logistics_delivery_cleaned.csv"))

C:\Users\91727\logistics_delivery_cleaned.csv
File exists: True